language: go
env:
- GO111MODULE=on

go:
- 1.16.x

script:
- cd $GOPATH/src/github.com/yahoo/k8s-athenz-istio-auth
- go build -v -race ./...
- diff -u <(echo -n) <(gofmt -d .)
- go vet ./...
- go test -v -race ./...

after_script:
- cd $GOPATH/src; mkdir k8s.io; cd k8s.io
- git clone https://github.com/kubernetes/kubernetes.git; cd kubernetes; git checkout release-1.17
- GO111MODULE=auto make WHAT=cmd/kube-apiserver
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime
- cd $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/kube-openapi; go mod init
- cd $GOPATH/src/github.com/yahoo/k8s-athenz-istio-auth/test/integration; go test -v ./...

branches:
  only: 
    - master
    - authzpolicy
    - authztest
    - default-ap
