language: go
env:
- GO111MODULE=on

go:
- 1.12.x

script:
- pwd
#- go build -v -race ./...
#- diff -u <(echo -n) <(gofmt -d .)
#- go vet ./...
#- go test -v -race ./...

after_script:
- cd /home/travis/gopath/src
- mkdir k8s.io
- cd k8s.io
- git clone https://github.com/kubernetes/kubernetes.git
- cd kubernetes
- git checkout release-1.11
- cd /home/travis/gopath/src/github.com/yahoo/k8s-athenz-istio-auth/test/integration
- go test -v ./...

branches:
  only: 
    - master
