language: go
env:
- GO111MODULE=on

go:
- 1.12.x

script:
- pwd
#- go build -v -race ./...
#- diff -u <(echo -n) <(gofmt -d .)
#- go vet ./...
#- go test -v -race ./...

after_script:
- git clone https://github.com/kubernetes/kubernetes.git
- git checkout release-1.11

branches:
  only: 
    - master
