language: go
env:
- GO111MODULE=on

go:
- 1.12.x

before_travis_install_go_dependencies:
- echo 'foobar'

script:
- pwd
- cd $GOPATH/src
- mkdir istio.io; cd istio.io
- git clone https://github.com/istio/istio.git; cd istio; git checkout eec7a74473de
- cd pilot/pkg/config/kube/crd
- git show d71e7927b040e873bf3053cd4c840bd42010a57:./controller/client.go > client.go
- go build -v -race ./...
- diff -u <(echo -n) <(gofmt -d .)
- go vet ./...
- go test -v -race ./...

after_script:
- cd $GOPATH/src; mkdir k8s.io; cd k8s.io
- git clone https://github.com/kubernetes/kubernetes.git; cd kubernetes; git checkout release-1.11
- GO111MODULE=auto make WHAT=cmd/kube-apiserver
- go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/kube-openapi; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/client-go; go mod init
- cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/api; go mod init
- cd $GOPATH/src/github.com/yahoo/k8s-athenz-istio-auth/test/integration; go test -v ./...

branches:
  only: 
    - master
