[[override]]
  name = "k8s.io/client-go"
  branch = "release-8.0" # kubernetes-1.11

[[constraint]]
  name = "istio.io/api"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "github.com/yahoo/athenz"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
