shared:
  image: golang:1.22.1
  environment:
    GO111MODULE: on

jobs:
  build:
    requires: [~pr, ~commit]
    steps:
      - init: cd $GOPATH/src/github.com/athenz/k8s-athenz-istio-auth
      - build: go build -v -race ./...
      - fmt: diff -u <(echo -n) <(gofmt -d .)
      - vet: go vet ./...
      - test: go test -v -race ./...
      - k8s: |
          cd $GOPATH/src
          mkdir -p k8s.io
          cd k8s.io
          git clone https://github.com/kubernetes/kubernetes.git
          cd kubernetes
          git checkout release-1.17
          GO111MODULE=auto make WHAT=cmd/kube-apiserver
      - k8s-cli: cd $GOPATH/src/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime
      - k8s-openapi:  | 
          cd $GOPATH/src/k8s.io/kubernetes/vendor/k8s.io/kube-openapi
          go mod init
      - integration-test: | 
          cd $GOPATH/src/github.com/athenz/k8s-athenz-istio-auth/test/integration
          go test -v ./...
