// Copyright 2019, VerizonMedia Inc.
// Licensed under the terms of the 3-Clause BSD license. See LICENSE file in github.com/yahoo/k8s-athenz-istio-auth
// for terms.
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AthenzDomainListerExpansion allows custom methods to be added to
// AthenzDomainLister.
type AthenzDomainListerExpansion interface{}

// AthenzDomainNamespaceListerExpansion allows custom methods to be added to
// AthenzDomainNamespaceLister.
type AthenzDomainNamespaceListerExpansion interface{}
