package v1

import (
	"github.com/jinzhu/copier"
	"github.com/yahoo/athenz/clients/go/zms"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +genclient:noStatus
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AthenzDomain is a top-level type
type AthenzDomain struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +optional
	Status DomainStatus `json:"status,omitempty"`
	// Athenz Signed Domain Spec
	Spec DomainSpec `json:"spec,omitempty"`
}

// custom spec
type DomainSpec struct {
	SignedDomain zms.SignedDomain `json:",inline"`
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainSpec.
func (in *DomainSpec) DeepCopy() *DomainSpec {
	if in == nil {
		return nil
	}
	out := new(DomainSpec)
	*out = *in
	if err := copier.Copy(&out.SignedDomain, &in.SignedDomain); err != nil {
		return nil
	}
	return out
}

// custom status
type DomainStatus struct {
	Name string
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// no client needed for list as it's been created in above
type AthenzDomainList struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ListMeta `json:"metadata,omitempty"`

	Items []AthenzDomain `json:"items"`
}
