apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-athenz-istio-auth
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.istio.io
  resources:
  - serviceroles
  - servicerolebindings
  - clusterrbacconfigs
  verbs:
  - list
  - get
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - athenz.io
  resources:
  - athenzdomains
  verbs:
  - watch
  - list
- apiGroups:
    - security.istio.io
  resources:
    - authorizationpolicies
  verbs:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch