apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-athenz-istio-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-athenz-istio-auth
subjects:
- kind: ServiceAccount
  name: k8s-athenz-istio-auth
