apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: k8s-athenz-istio-auth
  name: k8s-athenz-istio-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-athenz-istio-auth
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-athenz-istio-auth
    spec:
      serviceAccountName: k8s-athenz-istio-auth
      containers:
      - name: k8s-athenz-istio-auth
        image: local/k8s-athenz-istio-auth
