// Copyright 2019, Verizon Media Inc.
// Licensed under the terms of the 3-Clause BSD license. See LICENSE file in
// github.com/yahoo/k8s-athenz-istio-auth for terms.
// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated fake clientset.
package fake
