// Copyright 2019, Verizon Media Inc.
// Licensed under the terms of the 3-Clause BSD license. See LICENSE file in
// github.com/yahoo/k8s-athenz-istio-auth for terms.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/yahoo/k8s-athenz-istio-auth/pkg/client/clientset/versioned/typed/athenz/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAthenzV1 struct {
	*testing.Fake
}

func (c *FakeAthenzV1) AthenzDomains(namespace string) v1.AthenzDomainInterface {
	return &FakeAthenzDomains{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAthenzV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
