name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x' ]
    name: Go ${{ matrix.go }} build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - run:
         pwd;
         ls -la;
         mkdir k8s.io; cd k8s.io;
         pwd;
         ls -la;
